# Generated by Django 5.2.7 on 2025-10-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='logger.gym')),
            ],
            options={
                'unique_together': {('gym', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter_grade', models.CharField(blank=True, max_length=10)),
                ('concensus_grade', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('date_set', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setter', to=settings.AUTH_USER_MODEL)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulders', to='logger.wall')),
            ],
            options={
                'unique_together': {('wall', 'setter_grade', 'color', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascent_type', models.CharField(choices=[('flash', 'Flash'), ('send', 'Send')], max_length=20)),
                ('date_climbed', models.DateField(auto_now_add=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascents', to=settings.AUTH_USER_MODEL)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascents', to='logger.boulder')),
            ],
            options={
                'unique_together': {('climber', 'boulder')},
            },
        ),
    ]
