# Generated by Django 5.2.7 on 2025-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='num_ascents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
