# Generated by Django 5.2.7 on 2025-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_boulder_num_ascents'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='climbing_style',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('dynamic', 'Dynamic'), ('crimpy', 'Crimpy'), ('slopey', 'Slopey'), ('overhang', 'Overhang'), ('slab', 'Slab')], max_length=20),
        ),
        migrations.AddField(
            model_name='boulder',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20),
        ),
    ]
