# Generated by Django 5.2.7 on 2025-11-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_boulder_climbing_style_boulder_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boulder',
            name='concensus_grade',
        ),
        migrations.AlterField(
            model_name='boulder',
            name='climbing_style',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('power', 'Power'), ('slab', 'Slab'), ('coordination', 'Coordination'), ('electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='boulder',
            name='setter_grade',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7'), ('L8', 'L8')], max_length=10),
        ),
    ]
