# Generated by Django 5.2.7 on 2026-06-07 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_savedboulder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_opt_in', models.BooleanField(default=True, help_text='Whether the user participates in the gym leaderboard')),
                ('sends_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('only_me', 'Only Me')], default='everyone', help_text="Who can see this user's sends in the activity feed", max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
