# Generated by Django 5.2.7 on 2026-06-12 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_user_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wall',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='boulder',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='boulder',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_boulders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='setting_day',
            field=models.IntegerField(blank=True, help_text='Recurring weekly setting/reset day (0=Monday ... 6=Sunday)', null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='last_set',
            field=models.DateField(blank=True, help_text="Date this wall's routes were last reset/set.", null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='next_reset',
            field=models.DateField(blank=True, help_text='Manual override for the next reset date. If blank, it is computed from the gym setting day and queue order.', null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Position in the setting queue (lower = sooner). 0 is 'up next'."),
        ),
    ]
