# Generated by Django 5.2.7 on 2026-06-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_alter_wall_options_boulder_comments_boulder_tester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='zones_per_reset',
            field=models.PositiveIntegerField(default=2, help_text='Default number of zones reset together each setting day. The queue auto-rolls in batches of this size, one week apart.'),
        ),
    ]
