# Generated by Django 5.2.7 on 2026-04-28 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logger', '0007_add_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('membership', 'Membership'), ('class', 'Class'), ('event', 'Event')], max_length=20)),
                ('access_type', models.CharField(choices=[('sessions', 'Number of Sessions'), ('unlimited', 'Unlimited'), ('single_day', 'Single Day Access')], max_length=20)),
                ('num_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='logger.gym')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('gym', 'name', 'service_type')},
            },
        ),
    ]
