# Generated by Django 5.2.7 on 2026-04-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='used_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='yoactiv_service_id',
            field=models.CharField(blank=True, help_text='YoActiv service ID', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='yoactiv_service_variation_id',
            field=models.CharField(blank=True, help_text='YoActiv service variation ID', max_length=100),
        ),
    ]
