# Generated by Django 5.2.7 on 2026-04-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_service_used_sessions_service_yoactiv_service_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='service',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='service',
            name='used_sessions',
        ),
    ]
