# Generated by Django 5.2.7 on 2026-04-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service family name (e.g., 'Monthly Membership')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('membership', 'Membership'), ('class', 'Class'), ('event', 'Event')], max_length=20)),
                ('yoactiv_service_id', models.CharField(help_text='YoActiv service ID - groups all variations of this service', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='service',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in days for time-limited services', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text="Variation name (e.g., '1 Month', 'Premium', '10 Sessions')", max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_group',
            field=models.ForeignKey(default=1, help_text='Parent service group', on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='explore.servicegroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('service_group', 'yoactiv_service_variation_id')},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='yoactiv_service_id',
        ),
    ]
