# Generated by Django 5.2.7 on 2026-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_servicegroup_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='yoactiv_service_id',
            field=models.CharField(db_index=True, help_text='YoActiv service ID - groups all variations of this service', max_length=100),
        ),
    ]
