# Generated by Django 5.2.7 on 2026-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_alter_servicegroup_yoactiv_service_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.UniqueConstraint(fields=('name', 'yoactiv_service_id'), name='unique_servicegroup_name_yoactiv_id'),
        ),
    ]
