# Generated by Django 5.2.7 on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


def backfill_service_group_gym(apps, schema_editor):
    Gym = apps.get_model('logger', 'Gym')
    ServiceGroup = apps.get_model('explore', 'ServiceGroup')

    hoodi_gym = Gym.objects.filter(name='eQ Hoodi').order_by('id').first()
    if hoodi_gym is None:
        hoodi_gym = Gym.objects.create(name='eQ Hoodi')

    ServiceGroup.objects.filter(gym__isnull=True).update(gym_id=hoodi_gym.id)


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_add_userprofile'),
        ('explore', '0006_servicegroup_unique_servicegroup_name_yoactiv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='gym',
            field=models.ForeignKey(
                help_text='Gym that owns this service group',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='service_groups',
                to='logger.gym',
            ),
        ),
        migrations.RunPython(
            code=backfill_service_group_gym,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='gym',
            field=models.ForeignKey(
                help_text='Gym that owns this service group',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='service_groups',
                to='logger.gym',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='servicegroup',
            name='unique_servicegroup_name_yoactiv_id',
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.UniqueConstraint(
                fields=('gym', 'name', 'yoactiv_service_id'),
                name='unique_servicegroup_gym_name_yoactiv_id',
            ),
        ),
    ]
